import type { IngredientRule } from "@/lib/ingredient-engine";

export const fallbackIngredientRules: IngredientRule[] = [
  {
    ingredient_name: "partially hydrogenated oils",
    aliases: ["kismen hidrojenize yag", "hidrojenize bitkisel yag", "trans yag", "trans fat"],
    harmful_for: ["genel saglik"],
    severity: "critical",
    reason: "Trans-fat source with elevated cardiovascular risk.",
  },
  {
    ingredient_name: "sodium nitrite",
    aliases: ["sodyum nitrit", "e250"],
    harmful_for: ["genel saglik"],
    severity: "warning",
    reason: "Frequent intake of nitrite preservatives is not recommended.",
  },
  {
    ingredient_name: "sodium nitrate",
    aliases: ["sodyum nitrat", "e251", "e252"],
    harmful_for: ["genel saglik", "hipertansiyon"],
    severity: "warning",
    reason: "Frequent intake of nitrate preservatives is not recommended.",
  },
  {
    ingredient_name: "high fructose corn syrup",
    aliases: ["fruktoz glukoz surubu", "misir surubu", "high fructose corn syrup", "invert seker surubu"],
    harmful_for: ["genel saglik", "diyabet"],
    severity: "warning",
    reason: "High refined sugar load may adversely affect metabolic health.",
  },
  {
    ingredient_name: "sugar",
    aliases: ["seker", "toz seker", "glikoz", "fruktoz", "dekstroz", "glukoz surubu", "invert seker surubu", "misir surubu"],
    harmful_for: ["diyabet"],
    severity: "critical",
    reason: "Rapid blood sugar increase risk.",
  },
  {
    ingredient_name: "starch",
    aliases: ["nisasta", "modifiye nisasta"],
    harmful_for: ["diyabet"],
    severity: "warning",
    reason: "Carbohydrate load may raise glycemic response.",
  },
  {
    ingredient_name: "sorbitol",
    aliases: ["e420"],
    harmful_for: ["diyabet"],
    severity: "warning",
    reason: "Can affect glycemic control in high amounts.",
  },
  {
    ingredient_name: "aspartame",
    aliases: ["aspartam", "e951"],
    harmful_for: ["diyabet"],
    severity: "warning",
    reason: "Artificial sweetener; monitor frequent intake.",
  },
  {
    ingredient_name: "sucralose",
    aliases: ["sukraloz", "e955"],
    harmful_for: ["diyabet"],
    severity: "warning",
    reason: "Artificial sweetener; monitor frequent intake.",
  },
  {
    ingredient_name: "acesulfame potassium",
    aliases: ["asesulfam k", "asesulfam-k", "e950"],
    harmful_for: ["diyabet"],
    severity: "warning",
    reason: "Artificial sweetener often used in sugar-free products.",
  },
  {
    ingredient_name: "sodium",
    aliases: ["sodyum", "tuz", "salt", "sodyum klorur"],
    harmful_for: ["hipertansiyon"],
    severity: "critical",
    reason: "High sodium can increase blood pressure.",
  },
  {
    ingredient_name: "monosodium glutamate",
    aliases: ["msg", "e621"],
    harmful_for: ["hipertansiyon"],
    severity: "warning",
    reason: "May increase sodium intake.",
  },
  {
    ingredient_name: "sodium benzoate",
    aliases: ["e211"],
    harmful_for: ["hipertansiyon"],
    severity: "warning",
    reason: "Sodium-based preservative.",
  },
  {
    ingredient_name: "sodium nitrate",
    aliases: ["e251", "sodyum nitrat"],
    harmful_for: ["hipertansiyon"],
    severity: "warning",
    reason: "Processed additive with sodium burden.",
  },
  {
    ingredient_name: "citric acid",
    aliases: ["sitrik asit", "e330", "asitlik duzenleyici"],
    harmful_for: ["reflu", "gastrit"],
    severity: "warning",
    reason: "Acidic additive may aggravate reflux or gastric irritation.",
  },
  {
    ingredient_name: "carbon dioxide",
    aliases: ["karbondioksit", "co2"],
    harmful_for: ["reflu", "gastrit"],
    severity: "warning",
    reason: "Carbonation may worsen reflux and bloating symptoms.",
  },
  {
    ingredient_name: "caffeine",
    aliases: ["kafein", "coffee extract", "kahve ozu"],
    harmful_for: ["reflu", "gastrit"],
    severity: "warning",
    reason: "Caffeine can trigger reflux and stomach discomfort.",
  },
  {
    ingredient_name: "peppermint",
    aliases: ["nane", "mint"],
    harmful_for: ["reflu"],
    severity: "warning",
    reason: "Mint can relax LES and trigger reflux in sensitive users.",
  },
  {
    ingredient_name: "lactose",
    aliases: ["laktoz", "sut sekeri"],
    harmful_for: ["laktoz intoleransi"],
    severity: "critical",
    reason: "Primary trigger for lactose intolerance.",
  },
  {
    ingredient_name: "milk",
    aliases: ["sut", "sutu", "milk powder"],
    harmful_for: ["laktoz intoleransi"],
    severity: "critical",
    reason: "Contains lactose naturally.",
  },
  {
    ingredient_name: "whey",
    aliases: ["peynir alti suyu", "whey powder"],
    harmful_for: ["laktoz intoleransi"],
    severity: "warning",
    reason: "May contain residual lactose.",
  },
  {
    ingredient_name: "cream",
    aliases: ["krema"],
    harmful_for: ["laktoz intoleransi"],
    severity: "warning",
    reason: "Dairy derivative with lactose.",
  },
  {
    ingredient_name: "gluten",
    aliases: ["glutenli"],
    harmful_for: ["colyak"],
    severity: "critical",
    reason: "Unsafe for celiac disease.",
  },
  {
    ingredient_name: "wheat",
    aliases: ["bugday", "bugday unu"],
    harmful_for: ["colyak"],
    severity: "critical",
    reason: "Contains gluten proteins.",
  },
  {
    ingredient_name: "barley",
    aliases: ["arpa"],
    harmful_for: ["colyak"],
    severity: "critical",
    reason: "Contains gluten proteins.",
  },
  {
    ingredient_name: "rye",
    aliases: ["cavdar"],
    harmful_for: ["colyak"],
    severity: "critical",
    reason: "Contains gluten proteins.",
  },
  {
    ingredient_name: "triticale",
    aliases: ["tritikale"],
    harmful_for: ["colyak"],
    severity: "critical",
    reason: "Hybrid grain containing gluten.",
  },
  {
    ingredient_name: "soy lecithin",
    aliases: ["e322", "soya lesitini"],
    harmful_for: ["alerji soya"],
    severity: "warning",
    reason: "Potential soy allergen trace.",
  },
  {
    ingredient_name: "peanut oil",
    aliases: ["yer fistigi yagi"],
    harmful_for: ["alerji fistik"],
    severity: "critical",
    reason: "Peanut allergen risk.",
  },
  {
    ingredient_name: "peanut",
    aliases: ["yer fistigi", "fistik", "peanut"],
    harmful_for: ["alerji fistik"],
    severity: "critical",
    reason: "Peanut allergen risk.",
  },
  {
    ingredient_name: "peanut butter",
    aliases: ["yer fistigi ezmesi", "fistik ezmesi", "peanut butter"],
    harmful_for: ["alerji fistik"],
    severity: "critical",
    reason: "Peanut allergen risk.",
  },
  {
    ingredient_name: "egg powder",
    aliases: ["yumurta tozu", "yumurta"],
    harmful_for: ["alerji yumurta"],
    severity: "critical",
    reason: "Egg protein allergen.",
  },
  {
    ingredient_name: "sesame",
    aliases: ["susam"],
    harmful_for: ["alerji susam"],
    severity: "critical",
    reason: "Sesame allergen risk.",
  },
];
