import type { IngredientRule } from "@/lib/ingredient-engine";

export const fallbackIngredientRules: IngredientRule[] = [
  {
    ingredient_name: "partially hydrogenated oils",
    aliases: ["kismen hidrojenize yag", "hidrojenize bitkisel yag", "trans yag", "trans fat"],
    harmful_for: ["genel saglik"],
    severity: "critical",
    reason: "Trans yağ kaynağıdır; kardiyovasküler risk artışı ile ilişkilidir.",
  },
  {
    ingredient_name: "sodium nitrite",
    aliases: ["sodyum nitrit", "e250"],
    harmful_for: ["genel saglik"],
    severity: "warning",
    reason: "Nitrit koruyucuların sık tüketimi önerilmez.",
  },
  {
    ingredient_name: "sodium nitrate",
    aliases: ["sodyum nitrat", "e251", "e252"],
    harmful_for: ["genel saglik", "hipertansiyon"],
    severity: "warning",
    reason: "Nitrat koruyucuların sık tüketimi önerilmez.",
  },
  {
    ingredient_name: "high fructose corn syrup",
    aliases: ["fruktoz glukoz surubu", "misir surubu", "high fructose corn syrup", "invert seker surubu"],
    harmful_for: ["genel saglik", "diyabet"],
    severity: "warning",
    reason: "Yüksek rafine şeker yükü metabolik sağlığı olumsuz etkileyebilir.",
  },
  {
    ingredient_name: "sugar",
    aliases: ["seker", "toz seker", "glikoz", "fruktoz", "dekstroz", "glukoz surubu", "invert seker surubu", "misir surubu"],
    harmful_for: ["diyabet"],
    severity: "critical",
    reason: "Kan şekerini hızlı yükseltme riski taşır.",
  },
  {
    ingredient_name: "starch",
    aliases: ["nisasta", "modifiye nisasta"],
    harmful_for: ["diyabet"],
    severity: "warning",
    reason: "Karbonhidrat yükü glisemik yanıtı artırabilir.",
  },
  {
    ingredient_name: "sorbitol",
    aliases: ["e420"],
    harmful_for: ["diyabet"],
    severity: "warning",
    reason: "Yüksek miktarda glisemik kontrolü etkileyebilir.",
  },
  {
    ingredient_name: "aspartame",
    aliases: ["aspartam", "e951"],
    harmful_for: ["diyabet"],
    severity: "warning",
    reason: "Yapay tatlandırıcıdır; sık tüketimi sınırlandırılmalıdır.",
  },
  {
    ingredient_name: "sucralose",
    aliases: ["sukraloz", "e955"],
    harmful_for: ["diyabet"],
    severity: "warning",
    reason: "Yapay tatlandırıcıdır; sık tüketimi sınırlandırılmalıdır.",
  },
  {
    ingredient_name: "acesulfame potassium",
    aliases: ["asesulfam k", "asesulfam-k", "e950"],
    harmful_for: ["diyabet"],
    severity: "warning",
    reason: "Şekersiz ürünlerde sık kullanılan yapay tatlandırıcıdır.",
  },
  {
    ingredient_name: "sodium",
    aliases: ["sodyum", "tuz", "salt", "sodyum klorur"],
    harmful_for: ["hipertansiyon"],
    severity: "critical",
    reason: "Yüksek sodyum kan basıncını artırabilir.",
  },
  {
    ingredient_name: "monosodium glutamate",
    aliases: ["msg", "e621"],
    harmful_for: ["hipertansiyon"],
    severity: "warning",
    reason: "Toplam sodyum alımını artırabilir.",
  },
  {
    ingredient_name: "sodium benzoate",
    aliases: ["e211"],
    harmful_for: ["hipertansiyon"],
    severity: "warning",
    reason: "Sodyum bazlı koruyucudur.",
  },
  {
    ingredient_name: "sodium nitrate",
    aliases: ["e251", "sodyum nitrat"],
    harmful_for: ["hipertansiyon"],
    severity: "warning",
    reason: "Sodyum yükü getiren işlenmiş katkıdır.",
  },
  {
    ingredient_name: "citric acid",
    aliases: ["sitrik asit", "e330", "asitlik duzenleyici"],
    harmful_for: ["reflu", "gastrit"],
    severity: "warning",
    reason: "Asidik katkı reflü ve mide irritasyonunu artırabilir.",
  },
  {
    ingredient_name: "carbon dioxide",
    aliases: ["karbondioksit", "co2"],
    harmful_for: ["reflu", "gastrit"],
    severity: "warning",
    reason: "Karbonasyon reflü ve şişkinlik semptomlarını artırabilir.",
  },
  {
    ingredient_name: "caffeine",
    aliases: ["kafein", "coffee extract", "kahve ozu"],
    harmful_for: ["reflu", "gastrit"],
    severity: "warning",
    reason: "Kafein reflü ve mide rahatsızlığını tetikleyebilir.",
  },
  {
    ingredient_name: "peppermint",
    aliases: ["nane", "mint"],
    harmful_for: ["reflu"],
    severity: "warning",
    reason: "Nane, hassas kişilerde reflüyü tetikleyebilir.",
  },
  {
    ingredient_name: "lactose",
    aliases: ["laktoz", "sut sekeri"],
    harmful_for: ["laktoz intoleransi"],
    severity: "critical",
    reason: "Laktoz intoleransında temel tetikleyicidir.",
  },
  {
    ingredient_name: "milk",
    aliases: ["sut", "sutu", "milk powder"],
    harmful_for: ["laktoz intoleransi"],
    severity: "critical",
    reason: "Doğal olarak laktoz içerir.",
  },
  {
    ingredient_name: "whey",
    aliases: ["peynir alti suyu", "whey powder"],
    harmful_for: ["laktoz intoleransi"],
    severity: "warning",
    reason: "Kalıntı laktoz içerebilir.",
  },
  {
    ingredient_name: "cream",
    aliases: ["krema"],
    harmful_for: ["laktoz intoleransi"],
    severity: "warning",
    reason: "Laktoz içerebilen süt türevidir.",
  },
  {
    ingredient_name: "gluten",
    aliases: ["glutenli"],
    harmful_for: ["colyak"],
    severity: "critical",
    reason: "Çölyak için güvenli değildir.",
  },
  {
    ingredient_name: "wheat",
    aliases: ["bugday", "bugday unu"],
    harmful_for: ["colyak"],
    severity: "critical",
    reason: "Gluten proteinleri içerir.",
  },
  {
    ingredient_name: "barley",
    aliases: ["arpa"],
    harmful_for: ["colyak"],
    severity: "critical",
    reason: "Gluten proteinleri içerir.",
  },
  {
    ingredient_name: "rye",
    aliases: ["cavdar"],
    harmful_for: ["colyak"],
    severity: "critical",
    reason: "Gluten proteinleri içerir.",
  },
  {
    ingredient_name: "triticale",
    aliases: ["tritikale"],
    harmful_for: ["colyak"],
    severity: "critical",
    reason: "Gluten içeren hibrit tahıldır.",
  },
  {
    ingredient_name: "soy lecithin",
    aliases: ["e322", "soya lesitini"],
    harmful_for: ["alerji soya"],
    severity: "warning",
    reason: "Soya alerjeni izi içerebilir.",
  },
  {
    ingredient_name: "peanut oil",
    aliases: ["yer fistigi yagi"],
    harmful_for: ["alerji fistik"],
    severity: "critical",
    reason: "Yer fıstığı alerjeni riski taşır.",
  },
  {
    ingredient_name: "peanut",
    aliases: ["yer fistigi", "fistik", "peanut"],
    harmful_for: ["alerji fistik"],
    severity: "critical",
    reason: "Yer fıstığı alerjeni riski taşır.",
  },
  {
    ingredient_name: "peanut butter",
    aliases: ["yer fistigi ezmesi", "fistik ezmesi", "peanut butter"],
    harmful_for: ["alerji fistik"],
    severity: "critical",
    reason: "Yer fıstığı alerjeni riski taşır.",
  },
  {
    ingredient_name: "egg powder",
    aliases: ["yumurta tozu", "yumurta"],
    harmful_for: ["alerji yumurta"],
    severity: "critical",
    reason: "Yumurta proteini alerjenidir.",
  },
  {
    ingredient_name: "sesame",
    aliases: ["susam"],
    harmful_for: ["alerji susam"],
    severity: "critical",
    reason: "Susam alerjeni riski taşır.",
  },
];
