insert into public.ingredient_rules (ingredient_name, aliases, harmful_for, severity, reason)
values
  ('sugar', array['seker', 'glucose syrup', 'fruktoz', 'dekstroz', 'maltose', 'misir surubu'], array['diyabet'], 'critical', 'Rapid blood sugar increase risk.'),
  ('glucose', array['glikoz', 'dextrose'], array['diyabet'], 'critical', 'Direct glucose source.'),
  ('fructose', array['fruktoz', 'high fructose corn syrup'], array['diyabet'], 'warning', 'Can still elevate blood sugar load.'),
  ('aspartame', array['aspartam', 'e951'], array['diyabet'], 'warning', 'Artificial sweetener; monitor frequent intake.'),
  ('sucralose', array['sukraloz', 'e955'], array['diyabet'], 'warning', 'Artificial sweetener; monitor frequent intake.'),
  ('acesulfame potassium', array['asesulfam k', 'asesulfam-k', 'e950'], array['diyabet'], 'warning', 'Artificial sweetener commonly used in sugar-free products.'),
  ('sorbitol', array['sorbitol', 'e420'], array['diyabet'], 'warning', 'May impact glycemic control in high amounts.'),
  ('starch', array['nisasta', 'modified starch'], array['diyabet'], 'info', 'Monitor serving size due to carbohydrate content.'),
  ('sodium', array['tuz', 'salt', 'sodyum klorur'], array['hipertansiyon'], 'critical', 'High sodium can raise blood pressure.'),
  ('monosodium glutamate', array['msg', 'e621'], array['hipertansiyon'], 'warning', 'May contribute to sodium intake.'),
  ('sodium benzoate', array['e211'], array['hipertansiyon'], 'warning', 'Sodium-based preservative.'),
  ('sodium nitrate', array['e251'], array['hipertansiyon'], 'warning', 'Processed additive with sodium load.'),
  ('citric acid', array['sitrik asit', 'e330', 'asitlik duzenleyici'], array['reflu', 'gastrit'], 'warning', 'Acidic additive may aggravate reflux or gastric irritation.'),
  ('carbon dioxide', array['karbondioksit', 'co2'], array['reflu', 'gastrit'], 'warning', 'Carbonation may worsen reflux and bloating symptoms.'),
  ('caffeine', array['kafein', 'coffee extract', 'kahve ozu'], array['reflu', 'gastrit'], 'warning', 'Caffeine can trigger reflux and stomach discomfort.'),
  ('peppermint', array['nane', 'mint'], array['reflu'], 'warning', 'Mint can relax LES and trigger reflux in sensitive users.'),
  ('lactose', array['laktoz', 'milk sugar'], array['laktoz intoleransi'], 'critical', 'Primary trigger for lactose intolerance.'),
  ('milk', array['sut'], array['laktoz intoleransi'], 'critical', 'Contains lactose naturally.'),
  ('whey', array['peynir alti suyu', 'whey powder'], array['laktoz intoleransi'], 'warning', 'Often contains residual lactose.'),
  ('cream', array['krema'], array['laktoz intoleransi'], 'warning', 'Dairy derivative with lactose content.'),
  ('cheese', array['peynir'], array['laktoz intoleransi'], 'info', 'Some cheeses still contain lactose.'),
  ('gluten', array['bugday proteini'], array['colyak'], 'critical', 'Unsafe for celiac disease.'),
  ('wheat', array['bugday'], array['colyak'], 'critical', 'Contains gluten.'),
  ('barley', array['arpa'], array['colyak'], 'critical', 'Contains gluten proteins.'),
  ('rye', array['cavdar'], array['colyak'], 'critical', 'Contains gluten proteins.'),
  ('triticale', array['tritikale'], array['colyak'], 'critical', 'Hybrid grain containing gluten.'),
  ('malt extract', array['malt ozu'], array['colyak'], 'warning', 'Often barley-derived.'),
  ('soy lecithin', array['e322'], array['alerji soya'], 'warning', 'Potential soy allergen trace.'),
  ('peanut oil', array['yer fistigi yagi'], array['alerji fistik'], 'critical', 'Peanut allergen risk.'),
  ('peanut', array['yer fistigi', 'fistik', 'peanut'], array['alerji fistik'], 'critical', 'Peanut allergen risk.'),
  ('peanut butter', array['yer fistigi ezmesi', 'fistik ezmesi', 'peanut butter'], array['alerji fistik'], 'critical', 'Peanut allergen risk.'),
  ('egg powder', array['yumurta tozu'], array['alerji yumurta'], 'critical', 'Egg protein allergen.'),
  ('sesame', array['susam'], array['alerji susam'], 'critical', 'Sesame allergen risk.');
